---
- name: Watchtower Docker Container
  docker_container:
    name: watchtower
    image: containrrr/watchtower
    pull: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      WATCHTOWER_NOTIFICATIONS: slack
      WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: "{{ watchtower_slack_url }}"
      WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER: "{{ watchtower_slack_id }}"
      WATCHTOWER_NOTIFICATION_SLACK_CHANNEL: "{{ watchtower_slack_channel }}"
    command: "{{ watchtower_command }}"
    restart_policy: unless-stopped
    memory: 1g