---
- name: Create Navidrome Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ navidrome_data_directory }}/data"
    - "{{ navidrome_data_directory }}/playlists"

- name: Navidrome Docker Container
  docker_container:
    name: navidrome
    image: deluan/navidrome:latest
    pull: true
    command: --port 81
    network_mode: 
      - service:lazytainer
    depends_on: 
      - lazytainer
    volumes:
      - "{{ navidrome_data_directory }}/data:/data:rw"
      - "{{ navidrome_music_directory }}:/music:ro"
    ports:
      - "{{ navidrome_port }}:4533"
    env:
      ND_SCANINTERVAL: 1m
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
      ND_SPOTIFY_ID: "{{ ND_SPOTIFY_ID }}"
      ND_SPOTIFY_SECRET: "{{ ND_SPOTIFY_SECRET }}"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.backend: "navidrome"
      traefik.frontend.rule: "Host:navidrome.{{ ansible_nas_domain }}"
      traefik.enable: "{{ navidrome_available_externally }}"
      traefik.port: "4533"
      lazytainer.marker: "lazytainer"
    dns_servers: "{{ DNS_servers}}"