---
- name: Create Lazytainer container
  docker_container:
    name: lazytainer
    image: ghcr.io/vmorganp/lazytainer:master
    pull: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    env:
      PORT: "81"           # comma separated list of ports...or just the one 
      LABEL: "lazytainer:     # value of lazytainer.marker for other containers that lazytainer checks
      # TIMEOUT: 30           # OPTIONAL number of seconds to let container idle
      # MINPACKETTHRESH: 10   # OPTIONAL number of packets that must be recieved to keepalive/start container 
      # POLLRATE: 1           # OPTIONAL number of seconds to sleep between polls
      # VERBOSE: true         # probably set this to false unless you're debugging or doing the initial demo
    ports:
      - "{{ lazytainer_port_http }}:81"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.backend: "lazytainer"
      traefik.frontend.rule: "Host:lazytainer.{{ ansible_nas_domain }}"
      traefik.enable: "{{ lazytainer_available_externally }}"
      traefik.port: "81"