---
- name: Create Semaphore Directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ semaphore_data_directory }}/semaphore"
    - "{{ semaphore_data_directory }}/semaphore-db"

- name: Create MySQL container for Semaphore
  docker_container:
    name: mysql-semaphore
    image: mysql:5.7
    pull: true
    volumes:
      - "{{ semaphore_data_directory }}/mysql:/var/lib/mysql:rw"
    ports:
      - "3306:3306"
    env:
      MYSQL_DATABASE: "semaphore"
      MYSQL_USER: "semaphore"
      MYSQL_PASSWORD: "{{ semaphore_db_password }}"
      MYSQL_ROOT_PASSWORD: "{{ semaphore_root_db_password }}"
    restart_policy: unless-stopped
    memory: 1g

- name: Create Ansible Semaphore container
  docker_container:
    name: ansible-semaphore
    image: ansiblesemaphore/semaphore:latest
    pull: true
    links:
        - mysql-semaphore:db
    volumes:
      - "{{ semaphore_data_directory }}/semaphore:/etc/semaphore/:rw"
    ports:
      - "{{ semaphore_port_http }}:3000"
    env:
      SEMAPHORE_ADMIN: "admin"
      SEMAPHORE_ADMIN_EMAIL: "esfateev@gmail.com"
      SEMAPHORE_ADMIN_NAME: "admin"
      SEMAPHORE_ADMIN_PASSWORD: "{{ semaphore_admin_password }}"
      SEMAPHORE_DB: "semaphore"
      SEMAPHORE_DB_HOST: "db"
      SEMAPHORE_DB_PASS: "{{ semaphore_db_password }}"
      SEMAPHORE_DB_PORT: "3306"
      SEMAPHORE_DB_USER: "semaphore"
      SEMAPHORE_PLAYBOOK_PATH: "/tmp/semaphore/"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.backend: "tower"
      traefik.frontend.rule: "Host:tower.{{ ansible_nas_domain }}"
      traefik.enable: "{{ tower_available_externally }}"
      traefik.port: "3000"