- name: Grab auth creds
  include_vars:  './vars/creds.yml'
  no_log: 'yes'

- name: Create user
  user:
    name: "{{ username }}"
    state: present
    create_home: yes
    group: sudo
    shell: /bin/bash

- name: Change user password
  user:
    name: "{{ username }}"
    update_password: always
    password: "{{ newpassword|password_hash('sha512') }}"

- name: Set authorized keys taken from url
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "https://github.com/{{ AuthKeyGitHub }}"