---
- name: Create ansible-nas group
  group:
    name: ansible-nas
    state: present

- name: Create ansible-nas user
  user:
    name: ansible-nas
    state: present
    system: yes
    update_password: on_create
    create_home: no
    group: ansible-nas
    shell: /usr/sbin/nologin

- name: Create user
  user:
    name: "{{ UserName }}"
    state: present
    create_home: yes
    group: sudo
    shell: /bin/bash

- name: Set authorized keys taken from url
  authorized_key:
    user: "{{ UserName }}"
    state: present
#    key: "https://github.com/{{ AuthKeyGitHub }}"
    key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"