---
- name: install python3-pip
  apt:
    name: python3-pip
    state: present
  register: result
  until: result is succeeded

- name: 'Remove docker-py python module'
  pip:
    name: docker-py
    state: absent
  register: result
  until: result is succeeded

- name: 'Install docker python module'
  pip:
    name: docker
    state: present
  register: result
  until: result is succeeded

# - name: "Mount USB-drive to nas-point"
#   mount:
#     path: "{{ samba_shares_root }}"
#     src: UUID=b63cba41-16d3-4583-b4c8-eea4d6661035
#     fstype: ext4
#     opts: noatime
#     state: mounted

- name: "Permission share directories"
  file:
    path: "{{ item.path }}"
    state: directory
    owner: ansible-nas
    group: ansible-nas
    mode: "u=rwX,g=rwX,o=rX"
    recurse: false
  loop: "{{ samba_shares }}"

- name: create docker home
  file:
    path: "{{ docker_home }}"
    mode: 0755
    state: directory

- name: Ensure group "docker" exists with correct gid
  ansible.builtin.group:
    name: docker
    state: present

- name: add user account to docker group
  user:
    name: "{{ ansible_nas_user }}"
    groups: docker
    append: yes

- name: update docker home from install default
  template:
    src: docker/daemon.json
    dest: /etc/docker/daemon.json
  register: docker_config

- name: restart docker
  service:
     name: docker
     state: restarted
  when: docker_config.changed
  tags:
    - skip_ansible_lint